# Site
name: 'TECH a Look!'
description: 'If you are Techie like me, you shall find this blog posts useful to you. You shall find Useful Articles, Programming Language Tips and Tricks, Code Snippets, Knowledge Base, My Personal Experiences and some fun stuff. Happy Reading'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'https://www.srinivasakumar.com'
disqus: 'pragna'
email: 'srinivasakumar.a@live.com'
mailchimp-list: 'https://github.us17.list-manage.com/subscribe/post?u=498d6dddeb9e551be969fb68c&amp;id=f74e1e2fb1'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    srini:
      name:           Srini
      site:           https://www.srinivasakumar.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "I'm an Entrepreneur, SAP Developer, Flutter Mobile App Developer, Marketer and a Photographer."
      email:          srinivasakumar.a@live.com
      twitter:        https://twitter.com/ASrinivasaKumar

  #  jane:
  #    name:           Jane
  #    site:           https://www.wowthemes.net
  #    avatar:         /assets/images/avatar2.jpg
  #    bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
  #    email:          fakemail@gmail.com
  #    twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: srini
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
